---
- name: Install Nginx
  yum:
    name: nginx
    state: present
  notify: "Restart Nginx"
- name: Configuration Default
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: "Restart Nginx"